# Generated by Django 4.2.3 on 2023-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image1',
            field=models.ImageField(blank=True, default='images/actualites/default.png', max_length=255, null=True, upload_to='images/actualites/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image2',
            field=models.ImageField(blank=True, default='images/actualites/default.png', max_length=255, null=True, upload_to='images/actualites/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image3',
            field=models.ImageField(blank=True, default='images/actualites/default.png', max_length=255, null=True, upload_to='images/actualites/'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='image4',
            field=models.ImageField(blank=True, default='images/actualites/default.png', max_length=255, null=True, upload_to='images/actualites/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image1',
            field=models.ImageField(blank=True, default='images/events/default.png', max_length=255, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image2',
            field=models.ImageField(blank=True, default='images/events/default.png', max_length=255, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image3',
            field=models.ImageField(blank=True, default='images/events/default.png', max_length=255, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, default='images/participants/default.png', max_length=255, null=True, upload_to='images/participants/'),
        ),
    ]
