# Generated by Django 4.2.3 on 2023-08-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0002_alter_actualite_image1_alter_actualite_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualite',
            old_name='paragraphe1',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='paragraphe2',
        ),
        migrations.RemoveField(
            model_name='actualite',
            name='paragraphe3',
        ),
        migrations.AddField(
            model_name='actualite',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edition_actualite', to='vitrineApp.edition'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='soustitre',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
