# Generated by Django 4.2.3 on 2023-08-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0003_rename_paragraphe1_actualite_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='date',
        ),
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, default='images/actualites/default.png', max_length=255, null=True, upload_to='images/actualites/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
