# Generated by Django 4.2.3 on 2023-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0004_rename_image1_evenement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='date',
        ),
        migrations.AddField(
            model_name='evenement',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
