# Generated by Django 4.2.3 on 2023-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0005_remove_evenement_date_evenement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
