# Generated by Django 4.2.3 on 2023-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0007_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='reponse',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
