# Generated by Django 4.2.3 on 2023-08-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='CategorieItem',
        ),
    ]
