# Generated by Django 4.2.3 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerieApp', '0002_rename_categorie_categorieitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='media/images/galeries/default.png', max_length=255, null=True, upload_to='media/images/galeries/'),
        ),
    ]
