# Generated by Django 4.2.3 on 2023-08-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerieApp', '0003_item_auteur_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
