# Generated by Django 4.2.3 on 2023-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerieApp', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='images/galeries/default.png', max_length=255, null=True, upload_to='images/galeries/'),
        ),
    ]
