# Generated by Django 4.2.3 on 2023-09-05 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0008_alter_faq_question_alter_faq_reponse'),
        ('boutiqueApp', '0003_alter_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='recette',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='FaqProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_produit', to='vitrineApp.faq')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_faq', to='boutiqueApp.produit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
